---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-authentik
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      storageClassName: nfs-csi
      volumeMode: Filesystem
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      dataChecksums: true
      encoding: "UTF8"
  managed:
    roles:
      - name: authentik
        createdb: true
        login: true
        superuser: false
        createrole: false
        inRoles:
          - pg_monitor
          - pg_signal_backend
