---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  annotations:
  name: authentik-secret-key
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
spec:
  externalSecretName: authentik-secret-key
  externalSecretSpec:
    data:
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: authentik-secret-key/credential
          metadataPolicy: None
        secretKey: authentik-secret-key
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword-cluster
    target:
      creationPolicy: Owner
      deletionPolicy: Retain
  namespaceSelector:
    matchLabels:
      app: authentik
  refreshTime: 2m
