---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  source:
    helm:
      valueFiles:
        - $values/applications/external-secrets/overlays/kind/values.yaml
  sources:
    - repoURL: https://charts.external-secrets.io/
      chart: external-secrets
      targetRevision: 0.19.2
      helm:
        valueFiles:
          - $values/applications/external-secrets/overlays/kind/values.yaml
    - repoURL: https://github.com/dselders/argocd-app-of-apps.git
      targetRevision: main
      ref: values
