---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: application-patch.yaml
    target:
      kind: Application
      name: cloudnative-pg-operator
configMapGenerator:
  - name: cnpg-kind-values
    files:
      - values.yaml
