---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: onepassword-cluster
spec:
  provider:
    onepasswordSDK:
      auth:
        serviceAccountSecretRef:
          key: token
          name: onepassword-service-account-token
          namespace: kube-system
      vault: homelab
