---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  sources:
    - repoURL: https://github.com/dselders/argocd-app-of-apps.git
      targetRevision: main
      path: manifests/authentik
    - repoURL: https://charts.goauthentik.io
      chart: authentik
      targetRevision: 2025.8.1
      helm:
        valueFiles:
          - $values/charts/authentik/values.yaml
    - repoURL: https://github.com/dselders/argocd-app-of-apps.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    managedNamespaceMetadata:
      labels:
        app: authentik
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
