---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  sources:
    - repoURL: https://charts.external-secrets.io/
      chart: external-secrets
      targetRevision: 0.19.2
    - repoURL: https://github.com/dselders/argocd-app-of-apps.git
      targetRevision: main
      path: manifests/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        app: external-secrets-operator
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
