---
name: Validate ArgoCD Applications

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Validate Configurations
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install just
        uses: extractions/setup-just@v2
      
      - name: Install validation tools
        run: |
          # Kustomize
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/
          
          # yamllint
          pip install yamllint
          
          # ArgoCD CLI
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
          rm argocd-linux-amd64
          
          # kubeconform
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar xz
          sudo mv kubeconform /usr/local/bin/
      
      - name: Validate YAML syntax
        run: just lint
      
      - name: Validate Kustomize builds
        run: just kustomize-build
      
      - name: Validate ArgoCD applications
        run: just argocd-validate
      
      - name: Validate Kubernetes resources
        run: just k8s-validate
      
      - name: Run full validation suite
        run: just validate